version: '2'

services:
  db:
    image: mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tien
      MYSQL_PASSWORD: tien
      MYSQL_DATABASE: test_db

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - db
    links:
      - db
